$(info )
$(info 'EZTANK - Makefile RELEASE' )
$(info )

#	Colors --------------------------------------------------------------------
RED    := $(shell tput -Txterm setaf 1)
GREEN  := $(shell tput -Txterm setaf 2)
YELLOW := $(shell tput -Txterm setaf 3)
BLUE   := $(shell tput -Txterm setaf 4)
RESET  := $(shell tput -Txterm sgr0)



#	Executable Name -----------------------------------------------------------
TARGETNAME:=libeztank.so

#	Source Folders ------------------------------------------------------------
SRCDIR:=./src

#	Work Folders --------------------------------------------------------------
WRKDIR:=./release
OBJDIR:=$(WRKDIR)/obj
DEPDIR:=$(WRKDIR)/dep
BINDIR:=$(WRKDIR)/bin

#	Install Folders -----------------------------------------------------------
INSTALL:=../run/release/libs

#	Work Files ----------------------------------------------------------------
SRCS:=$(shell find $(SRCDIR) -name "*.c")

DEPSTMP:=$(SRCS:.c=.d)
DEPS:=$(subst $(SRCDIR),$(DEPDIR),$(DEPSTMP))

OBJSTMP:=$(patsubst %.c,%.o,$(SRCS))
OBJS:=$(subst $(SRCDIR),$(OBJDIR),$(OBJSTMP))

TARGET:=$(BINDIR)/$(TARGETNAME)



# Compile ---------------------------------------------------------------------
CC:=gcc
CCFLAGS:=-c -fPIC -fvisibility=hidden -I ./src/include
DEPFLAGS = -MMD -MP -MF $(DEPDIR)/$*.d 

# Link ------------------------------------------------------------------------
LD:=gcc
LDFLAGS:=-shared 
LDLIBS:=


#	Actions -------------------------------------------------------------------

build: $(TARGET)


all: clean zero build install 


$(TARGET): $(OBJS) 
	$(info  )
	$(info Linking ... )
	@echo -n "\t${YELLOW}"  
	$(LD) -o $@ $(LDFLAGS) $(LDLIBS) $^
	@echo -n "${RESET}"  
	$(info )


-include $(DEPS)

$(OBJDIR)/%.o: $(SRCDIR)/%.c
	@echo -n "\t${YELLOW}"  
	$(CC) -o $@ $(CCFLAGS) $(DEPFLAGS) $<
	@echo -n "${RESET}"  


clean:
	rm -rf $(WRKDIR)


help:
	@cat ./readme.txt


.PHONY: install
install:
	$(info )
	$(info Install ...)
	cp $(TARGET) $(INSTALL)/bin
	cp $(SRCDIR)/include/eztank.h $(INSTALL)/include
	cp $(SRCDIR)/include/ezvio.h $(INSTALL)/include

.PHONY: zero
zero:
	$(info )
	mkdir -p $(OBJDIR) $(DEPDIR) $(BINDIR)
	$(info )

.PHONY: info
info:
	$(info Target       : $(YELLOW)$(TARGET)$(RESET))
	$(info )
	$(info Working Dir  : $(PWD))
	$(info )
	$(info Sources      : $(SRCS))
	$(info Dependencies : $(DEPS))
	$(info Objects      : $(OBJS))
	$(info )
	$(info Install Dir  : $(INSTALL))
	$(info )
	@echo
	@echo "$(LD)  $(OBJS)  $(LDFLAGS) $(LDLIBS) -o $(TARGET) "
	@echo "$(CC) $(CCFLAGS) $(DEPFLAGS) $(INCLUDE) %.c -o %.o "
	
